/** Common lifts for first-launch catalog seeding. */
export const SEEDED_EXERCISES = [
  // Chest
  'Bench Press',
  'Incline Bench Press',
  'Decline Bench Press',
  'Dumbbell Bench Press',
  'Incline Dumbbell Press',
  'Chest Fly',
  'Cable Fly',
  'Push-up',
  'Dips',
  // Back
  'Deadlift',
  'Romanian Deadlift',
  'Barbell Row',
  'Dumbbell Row',
  'Lat Pulldown',
  'Pull-up',
  'Chin-up',
  'Seated Cable Row',
  'Face Pull',
  // Shoulders
  'Overhead Press',
  'Dumbbell Shoulder Press',
  'Lateral Raise',
  'Front Raise',
  'Rear Delt Fly',
  'Arnold Press',
  'Shrugs',
  // Legs
  'Back Squat',
  'Front Squat',
  'Goblet Squat',
  'Leg Press',
  'Bulgarian Split Squat',
  'Lunges',
  'Walking Lunges',
  'Leg Curl',
  'Leg Extension',
  'Calf Raise',
  'Hip Thrust',
  'Good Morning',
  // Arms
  'Barbell Curl',
  'Dumbbell Curl',
  'Hammer Curl',
  'Preacher Curl',
  'Tricep Pushdown',
  'Skull Crusher',
  'Close-Grip Bench Press',
  'Tricep Extension',
  // Core / misc
  'Plank',
  'Hanging Leg Raise',
  'Cable Crunch',
  'Ab Wheel',
  'Farmer Carry',
] as const;
